### ISSUE TITLE
검색 기능 추가해주세요

### ISSUE THREAD

**Issue by starrain1019** [2du/PHP-CueWiki#2]
한번 무료 호스팅에 깔아봤는데 검색 기능이 없네요...

**Comment by surplus-dev** [comment]
아마... 간단한 기능이야 그냥 오픈나무 알고리즘 떼오면 될 것 같긴한데

그 짝에도 하도 이슈가 쌓여있으니 이건 정말 짬날 때마다 할 것 같네요

**Comment by surplus-dev** [comment]
통합
