### ISSUE TITLE
JS 기반 렌더러가 있으니까

### ISSUE THREAD

**Issue by starrain1019** [2du/PHP-CueWiki#3]
오픈나무랑 연계하면 나무마크 문법 지원 가능한가요?

**Comment by surplus-dev** [comment]
@yangis1019 긁적긁적... 아직 그거 안 만들어서 음... 아마도 완성하면 가능할 듯 하네요

사실 이거 개발 다시 시작한 것도 그거랑 새로 만들 오리마크랑 좀 관련 있어서...

**Comment by surplus-dev** [comment]
통합
